FROM python:3.12-slim

WORKDIR /app

COPY requirements_test.txt .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt -r requirements_test.txt

ENV PYTHONPATH=/app
ENV ENVIRONMENT=test

CMD ["pytest", "tests/", "-v"]