services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    environment:
      - ENVIRONMENT=test
      - PYTHONPATH=/app
    command: python -m pytest tests/ -v