services:
  # Servicio principal para ejecutar los tests
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./test-results:/app/test-results
    environment:
      - ENVIRONMENT=test
      - PYTHONPATH=/app
    command: pytest

