FROM python:3.12-slim

WORKDIR /app

COPY requirements_test.txt .

RUN pip install --no-cache-dir -r requirements_test.txt

COPY ./app /app/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
