FROM python:3.12-slim

WORKDIR /app

COPY requirements_test.txt .

RUN pip install --no-cache-dir -r requirements_test.txt


COPY ./app /app/app

COPY ./tests /app/tests

CMD ["/app/run_tests_in_container.sh"]
